name: 'Pre-commit'
author: 'EnricoMi'
description: 'A GitHub Action that runs pre-commit'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    # FIXME: pin pre-commit<4 pending PyCQA/docformatter#287
    - name: install pre-commit
      run: python -m pip install 'pre-commit<4'
      shell: bash
    - name: show environment
      run: python -m pip freeze --local
      shell: bash
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
      shell: bash
