name: 'MyPy'
author: 'EnricoMi'
description: 'A GitHub Action that runs mypy'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements/types.txt
      shell: bash
    - uses: liskin/gh-problem-matcher-wrap@v2
      with:
        action: add
        linters: mypy
    - run: mypy --show-column-numbers github tests
      shell: bash
