import Framework

class NamedUser( Framework.TestCase ):
    def testAttributesOfOtherUser( self ):
        user = self.g.get_user( "nvie" )
        self.assertEqual( user.avatar_url, "https://secure.gravatar.com/avatar/c5a7f21b46df698f3db31c37ed0cf55a?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-140.png" )
        self.assertEqual( user.bio, None )
        self.assertEqual( user.blog, "http://nvie.com" )
        self.assertEqual( user.collaborators, None )
        self.assertEqual( user.company, "3rd Cloud" )
        self.assertEqual( user.created_at, "2009-05-12T21:19:38Z" )
        self.assertEqual( user.disk_usage, None )
        self.assertEqual( user.email, "vincent@3rdcloud.com" )
        self.assertEqual( user.followers, 296 )
        self.assertEqual( user.following, 41 )
        self.assertEqual( user.gravatar_id, "c5a7f21b46df698f3db31c37ed0cf55a" )
        self.assertEqual( user.hireable, False )
        self.assertEqual( user.html_url, "https://github.com/nvie" )
        self.assertEqual( user.id, 83844 )
        self.assertEqual( user.location, "Netherlands" )
        self.assertEqual( user.login, "nvie" )
        self.assertEqual( user.name, "Vincent Driessen" )
        self.assertEqual( user.owned_private_repos, None )
        self.assertEqual( user.plan, None )
        self.assertEqual( user.private_gists, None )
        self.assertEqual( user.public_gists, 16 )
        self.assertEqual( user.public_repos, 61 )
        self.assertEqual( user.total_private_repos, None )
        self.assertEqual( user.type, "User" )
        self.assertEqual( user.url, "https://api.github.com/users/nvie" )

    def testAttributesOfSelf( self ):
        user = self.g.get_user( "jacquev6" )
        self.assertEqual( user.avatar_url, "https://secure.gravatar.com/avatar/b68de5ae38616c296fa345d2b9df2225?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-140.png" )
        self.assertEqual( user.bio, "" )
        self.assertEqual( user.blog, "http://vincent-jacques.net" )
        self.assertEqual( user.collaborators, 0 )
        self.assertEqual( user.company, "Criteo" )
        self.assertEqual( user.created_at, "2010-07-09T06:10:06Z" )
        self.assertEqual( user.disk_usage, 16852 )
        self.assertEqual( user.email, "vincent@vincent-jacques.net" )
        self.assertEqual( user.followers, 13 )
        self.assertEqual( user.following, 24 )
        self.assertEqual( user.gravatar_id, "b68de5ae38616c296fa345d2b9df2225" )
        self.assertEqual( user.hireable, False )
        self.assertEqual( user.html_url, "https://github.com/jacquev6" )
        self.assertEqual( user.id, 327146 )
        self.assertEqual( user.location, "Paris, France" )
        self.assertEqual( user.login, "jacquev6" )
        self.assertEqual( user.name, "Vincent Jacques" )
        self.assertEqual( user.owned_private_repos, 5 )
        self.assertEqual( user.plan.name, "micro" )
        self.assertEqual( user.plan.collaborators, 1 )
        self.assertEqual( user.plan.space, 614400 )
        self.assertEqual( user.plan.private_repos, 5 )
        self.assertEqual( user.private_gists, 5 )
        self.assertEqual( user.public_gists, 1 )
        self.assertEqual( user.public_repos, 11 )
        self.assertEqual( user.total_private_repos, 5 )
        self.assertEqual( user.type, "User" )
        self.assertEqual( user.url, "https://api.github.com/users/jacquev6" )
