# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt
    - requirements: requirements/docs.txt
