import datetime
from typing import Any, Dict, Optional

from github.Auth import AppUserAuth
from github.GithubObject import NonCompletableGithubObject

class AccessToken(NonCompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def token(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def scope(self) -> str: ...
    @property
    def created(self) -> datetime.datetime: ...
    @property
    def expires_in(self) -> Optional[int]: ...
    @property
    def expires_at(self) -> Optional[datetime.datetime]: ...
    @property
    def refresh_token(self) -> Optional[str]: ...
    @property
    def refresh_expires_in(self) -> Optional[int]: ...
    @property
    def refresh_expires_at(self) -> Optional[datetime.datetime]: ...
    def as_app_user_auth(self) -> AppUserAuth: ...
