import datetime
from typing import Optional, Dict, Union, Callable

from github.Requester import Requester
from github.InstallationAuthorization import InstallationAuthorization

ACCESS_TOKEN_REFRESH_THRESHOLD_SECONDS: int = ...
ACCESS_TOKEN_REFRESH_THRESHOLD_DELTA: datetime.timedelta = ...

class AppAuthentication:
    app_id: Union[int, str] = ...
    private_key: str = ...
    jwt_expiry: int = ...
    jwt_issued_at: int = ...
    def __init__(
        self,
        app_id: Union[int, str],
        private_key: str,
        jwt_expiry: int = ...,
        jwt_issued_at: int = ...,
    ): ...
    def create_jwt(self) -> str: ...
