import datetime
from typing import Optional, Dict, Union, Callable

from github.Requester import Requester
from github.AppAuthentication import AppAuthentication
from github.InstallationAuthorization import InstallationAuthorization

ACCESS_TOKEN_REFRESH_THRESHOLD_SECONDS: int = ...
ACCESS_TOKEN_REFRESH_THRESHOLD_DELTA: datetime.timedelta = ...

def create_jwt(
    app_id: int = ...,
    private_key: str = ...,
    expiration: int = ...,
    issued_at: int = ...,
) -> str: ...

class AppInstallationAuthentication:
    app_id: Union[int, str] = ...
    private_key: str = ...
    app_auth: AppAuthentication = ...
    installation_id: int = ...
    token_permissions: Optional[Dict[str, str]] = ...
    jwt_expiry: int = ...
    jwt_issued_at: int = ...
    def __init__(
        self,
        app_id: Union[int, str],
        private_key: str,
        installation_id: int,
        token_permissions: Optional[Dict[str, str]] = ...,
        jwt_expiry: int = ...,
        jwt_issued_at: int = ...,
    ): ...
    def _get_access_token_func(
        self, requester: Requester
    ) -> Callable[[], InstallationAuthorization]: ...
    def __get_access_token(self, requester: Requester) -> InstallationAuthorization: ...
