from datetime import datetime
from typing import Any, Dict, Union

from github.GithubObject import CompletableGithubObject

class Artifact(CompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def node_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def size_in_bytes(self) -> int: ...
    @property
    def url(self) -> str: ...
    @property
    def archive_download_url(self) -> str: ...
    @property
    def expired(self) -> bool: ...
    @property
    def created_at(self) -> datetime: ...
    @property
    def updated_at(self) -> datetime: ...
    @property
    def expires_at(self) -> datetime: ...
