from typing import Dict

class AuthorizationApplication:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, str]) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def url(self) -> str: ...
