from datetime import datetime
from typing import Any, Dict, List

from github.GithubApp import GithubApp
from github.GithubObject import CompletableGithubObject
from github.PullRequest import PullRequest

class CheckRun(CompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def app(self) -> GithubApp: ...
    @property
    def check_suite(self) -> Dict[str, int]: ...
    @property
    def completed_at(self) -> datetime: ...
    @property
    def conclusion(self) -> str: ...
    @property
    def details_url(self) -> str: ...
    @property
    def external_id(self) -> str: ...
    @property
    def head_sha(self) -> str: ...
    @property
    def html_url(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def node_id(self) -> str: ...
    @property
    def output(self) -> Dict[str, Any]: ...
    @property
    def pull_requests(self) -> List[PullRequest]: ...
    @property
    def started_at(self) -> datetime: ...
    @property
    def status(self) -> str: ...
    @property
    def url(self) -> str: ...
