from typing import Any, Dict

import github.GithubObject
import github.CodeScanAlertInstanceLocation


class CodeScanAlertInstance(github.GithubObject.NonCompletableGithubObject):
    def __repr__(self) -> str: ...
    @property
    def ref(self) -> str: ...
    @property
    def analysis_key(self) -> str: ...
    @property
    def environment(self) -> str: ...
    @property
    def state(self) -> str: ...
    @property
    def commit_sha(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def location(self) -> github.CodeScanAlertInstanceLocation.CodeScanAlertInstanceLocation: ...
    @property
    def classifications(self) -> list[str]: ...

    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
