from typing import Any, Dict

import github.Tool
from github.GithubObject import NonCompletableGithubObject

class CodeScanningAnalysis(NonCompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def ref(self) -> str: ...
    @property
    def commit_sha(self) -> str: ...
    @property
    def analysis_key(self) -> str: ...
    @property
    def environment(self) -> str: ...
    @property
    def error(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def created_at(self) -> str: ...
    @property
    def results_count(self) -> int: ...
    @property
    def rules_count(self) -> int: ...
    @property
    def id(self) -> int: ...
    @property
    def url(self) -> str: ...
    @property
    def sarif_id(self) -> str: ...
    @property
    def tool(self) -> github.Tool.Tool: ...
    @property
    def deletable(self) -> bool: ...
    @property
    def warning(self) -> str: ...
