from typing import Dict

class CommitStats:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, int]) -> None: ...
    @property
    def additions(self) -> int: ...
    @property
    def deletions(self) -> int: ...
    @property
    def total(self) -> int: ...
