from typing import Any, Dict

from github.Dependency import Dependency
from github.GithubObject import NonCompletableGithubObject
from github.SecurityVulnerability import SecurityVulnerability

class DependabotAlert(NonCompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def created_at(self) -> str: ...
    @property
    def dependency(self) -> Dependency: ...
    @property
    def dismissed_at(self) -> str: ...
    @property
    def dismissed_comment(self) -> str: ...
    @property
    def dismissed_reason(self) -> str: ...
    @property
    def fixed_at(self) -> str: ...
    @property
    def html_url(self) -> str: ...
    @property
    def number(self) -> int: ...
    @property
    def security_vulnerability(self) -> SecurityVulnerability: ...
    @property
    def state(self) -> str: ...
    @property
    def updated_at(self) -> str: ...
    @property
    def url(self) -> str: ...
