from datetime import datetime
from typing import Any, Dict

from github.GithubObject import CompletableGithubObject
from github.NamedUser import NamedUser

class Deployment(CompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def url(self) -> str: ...
    @property
    def sha(self) -> str: ...
    @property
    def task(self) -> str: ...
    @property
    def payload(self) -> Dict[str, Any]: ...
    @property
    def original_environment(self) -> str: ...
    @property
    def environment(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def creator(self) -> NamedUser: ...
    @property
    def created_at(self) -> datetime: ...
    @property
    def updated_at(self) -> datetime: ...
    @property
    def statuses_url(self) -> str: ...
    @property
    def repository_url(self) -> str: ...
