from github.GithubObject import CompletableGithubObject
from typing import Any, Dict, Union
from github.GithubObject import CompletableGithubObject, _NotSetType
from github.NamedEnterpriseUser import NamedEnterpriseUser
from github.PaginatedList import PaginatedList

class EnterpriseConsumedLicenses(CompletableGithubObject):
    def _repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def total_seats_consumed(self) -> int: ...
    @property
    def total_seats_purchased(self) -> int: ...
    @property
    def login(self) -> str: ...
    @property
    def url(self) -> str: ...
    def get_enterprise_users(
        self,
        filter_: Union[str, _NotSetType] = ...,
        role: Union[str, _NotSetType] = ...,
    ) -> PaginatedList[NamedEnterpriseUser]: ...
