import datetime
from typing import List
import github.GithubObject
import github.EnvironmentProtectionRule
import github.EnvironmentDeploymentBranchPolicy

class Environment(github.GithubObject.CompletableGithubObject):
    @property
    def created_at(self) -> datetime.datetime: ...
    @property
    def html_url(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def node_id(self) -> str: ...
    @property
    def protection_rules(
        self,
    ) -> List[github.EnvironmentProtectionRule.EnvironmentProtectionRule]: ...
    @property
    def updated_at(self) -> datetime.datetime: ...
    @property
    def url(self) -> str: ...
    @property
    def deployment_branch_policy(
        self,
    ) -> github.EnvironmentDeploymentBranchPolicy.EnvironmentDeploymentBranchPolicy: ...
