"""
Representation of the generated release notes returned by the release/generate-notes REST API endpoint.
"""

from typing import Any, Dict

from github.GithubObject import (
    Attribute,
    CompletableGithubObject,
    NotSet,
)


# New file named github/GeneratedReleaseNotes.py
class GeneratedReleaseNotes(CompletableGithubObject):
    """
    This class represents the release notes generated by the release/generate-notes REST API endpoint.

    The reference can be found here:
    https://docs.github.com/en/rest/releases/releases#generate-release-notes-content-for-a-release

    """

    def _initAttributes(self) -> None:
        self._name: Attribute[str] = NotSet
        self._body: Attribute[str] = NotSet

    def __repr__(self) -> str:
        return self.get__repr__({"name": self._name.value, "body": self._body.value})

    @property
    def name(self) -> str:
        return self._name.value

    @property
    def body(self) -> str:
        return self._body.value

    def _useAttributes(self, attributes: Dict[str, Any]) -> None:
        if "body" in attributes:
            self._body = self._makeStringAttribute(attributes["body"])
        if "name" in attributes:
            self._title = self._makeStringAttribute(attributes["name"])
