from typing import Union, Optional, Dict

import github
from github.AppAuthentication import AppAuthentication
from github.AppInstallationAuthentication import AppInstallationAuthentication
from github.Installation import Installation
from github.PaginatedList import PaginatedList
from github.Requester import Requester

class GithubIntegration:
    app_id: Union[int, str] = ...
    private_key: str = ...
    app_auth: AppAuthentication = ...
    base_url: str = ...
    jwt_expiry: int = ...
    jwt_issued_at: int = ...
    __requester: Requester = ...
    def __init__(
        self,
        app_id: Union[int, str],
        private_key: str,
        requester: Requester = ...,
    ) -> None: ...
    def _get_installed_app(self, url: str) -> Installation: ...
    def _get_headers(self) -> Dict[str, str]: ...
    def create_jwt(
        self, expiration: Optional[int] = ..., issued_at: Optional[int] = ...
    ) -> str: ...
    def get_app_installation_authentication(
        self,
        installation_id: int,
        permissions: Optional[Dict[str, str]] = ...,
        jwt_expiry: int = ...,
        jwt_issued_at: int = ...,
    ):
        AppInstallationAuthentication
    def get_github_for_installation(
        self,
        installation_id: int,
        permissions: Optional[Dict[str, str]] = ...,
        jwt_expiry: int = ...,
        jwt_issued_at: int = ...,
    ):
        github.Github
    def get_app_installation(self, installation_id: int) -> Installation: ...
    def get_installation(self, owner: str, repo: str) -> Installation: ...
    def get_installations(self) -> PaginatedList[Installation]: ...
    def get_org_installation(self, org: str) -> Installation: ...
    def get_repo_installation(self, owner: str, repo: str) -> Installation: ...
    def get_user_installation(self, username: str) -> Installation: ...
