from typing import Dict


class GitignoreTemplate:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, str]) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def source(self) -> str: ...
