from typing import Any, Dict

class GitignoreTemplate:
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def source(self) -> str: ...
