from datetime import datetime
from github.NamedUser import NamedUser
from typing import (
    Dict,
    Union,
)


class GitReleaseAsset:
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Union[int, str, Dict[str, Union[str, int]]]]) -> None: ...
    @property
    def browser_download_url(self) -> str: ...
    @property
    def content_type(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...
    def delete_asset(self) -> bool: ...
    @property
    def download_count(self) -> int: ...
    @property
    def id(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def state(self) -> str: ...
    def update_asset(self, name: str, label: str = ...) -> GitReleaseAsset: ...
    @property
    def updated_at(self) -> datetime: ...
    @property
    def uploader(self) -> NamedUser: ...
    @property
    def url(self) -> str: ...
