from github.GitTreeElement import GitTreeElement
from typing import (
    Any,
    Dict,
    List,
)


class GitTree:
    def __repr__(self) -> str: ...
    @property
    def _identity(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(
        self,
        attributes: Dict[str, Any]
    ) -> None: ...
    @property
    def sha(self) -> str: ...
    @property
    def tree(self) -> List[GitTreeElement]: ...
    @property
    def url(self) -> str: ...
