from typing import (
    Any,
    Dict,
    Optional,
)


class GitTreeElement:
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def mode(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def sha(self) -> str: ...
    @property
    def size(self) -> Optional[int]: ...
    @property
    def type(self) -> str: ...
    @property
    def url(self) -> str: ...
