from typing import (
    Dict,
    Optional,
    Union,
)


class GitTreeElement:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Union[str, int]]) -> None: ...
    @property
    def mode(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def sha(self) -> str: ...
    @property
    def size(self) -> Optional[int]: ...
    @property
    def type(self) -> str: ...
    @property
    def url(self) -> str: ...
