from typing import Any, Dict

from github.GitAuthor import GitAuthor
from github.GitObject import GitObject

from github.GithubObject import CompletableGithubObject

class GitTag(CompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def message(self) -> str: ...
    @property
    def object(self) -> GitObject: ...
    @property
    def sha(self) -> str: ...
    @property
    def tag(self) -> str: ...
    @property
    def tagger(self) -> GitAuthor: ...
    @property
    def url(self) -> str: ...
