from datetime import datetime
from typing import Dict


class InstallationAuthorization:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, str]) -> None: ...
    @property
    def expires_at(self) -> datetime: ...
    @property
    def token(self) -> str: ...
