from datetime import datetime
from typing import Any, Dict

from github.NamedUser import NamedUser

from github.GithubObject import NonCompletableGithubObject

class InstallationAuthorization(NonCompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def expires_at(self) -> datetime: ...
    @property
    def on_behalf_of(self) -> NamedUser: ...
    @property
    def token(self) -> str: ...
    @property
    def permissions(self) -> dict: ...
    @property
    def repository_selection(self) -> str: ...
