from datetime import datetime
from typing import Any, Dict, List

from github.GithubObject import NonCompletableGithubObject
from github.NamedUser import NamedUser
from github.PaginatedList import PaginatedList
from github.Repository import Repository

class Installation(NonCompletableGithubObject):
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def access_tokens_url(self) -> str: ...
    @property
    def account(self) -> NamedUser: ...
    @property
    def app_id(self) -> int: ...
    @property
    def app_slug(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...
    @property
    def events(self) -> List[str]: ...
    @property
    def has_multiple_single_files(self) -> bool: ...
    @property
    def html_url(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def permissions(self) -> Dict[str, str]: ...
    @property
    def repositories_url(self) -> str: ...
    @property
    def repository_selection(self) -> str: ...
    @property
    def single_file_name(self) -> str: ...
    @property
    def single_file_paths(self) -> List[str]: ...
    @property
    def target_id(self) -> int: ...
    @property
    def target_type(self) -> str: ...
    @property
    def updated_at(self) -> datetime: ...
    def get_repos(self) -> PaginatedList[Repository]: ...
