from typing import (
    Dict,
    Optional,
    Union,
)


class IssuePullRequest:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Union[None, str]]) -> None: ...
    @property
    def diff_url(self) -> None: ...
    @property
    def html_url(self) -> None: ...
    @property
    def patch_url(self) -> None: ...
