from typing import Any, Dict

class IssuePullRequest:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def diff_url(self) -> str: ...
    @property
    def html_url(self) -> str: ...
    @property
    def patch_url(self) -> str: ...
