from typing import (
    Dict,
    List,
    Union,
)


class License:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Union[str, List[str], bool]]) -> None: ...
    @property
    def body(self) -> str: ...
    @property
    def conditions(self) -> List[str]: ...
    @property
    def description(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def limitations(self) -> List[str]: ...
    @property
    def name(self) -> str: ...
    @property
    def permissions(self) -> List[str]: ...
    @property
    def spdx_id(self) -> str: ...
