from datetime import (
    date,
    datetime,
)
from github.GithubObject import _NotSetType
from github.NamedUser import NamedUser
from github.PaginatedList import PaginatedList
from typing import (
    Dict,
    Optional,
    Union,
)


class Milestone:
    def __repr__(self) -> str: ...
    @property
    def _identity(self) -> int: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Union[str, int, Dict[str, Union[str, int]], None]]) -> None: ...
    @property
    def closed_issues(self) -> int: ...
    @property
    def creator(self) -> NamedUser: ...
    def delete(self) -> None: ...
    @property
    def description(self) -> str: ...
    @property
    def due_on(self) -> Optional[datetime]: ...
    def edit(
        self,
        title: str,
        state: Union[_NotSetType, str] = ...,
        description: Union[_NotSetType, str] = ...,
        due_on: Union[date, _NotSetType] = ...
    ) -> None: ...
    def get_labels(self) -> PaginatedList: ...
    @property
    def id(self) -> int: ...
    @property
    def labels_url(self) -> str: ...
    @property
    def number(self) -> int: ...
    @property
    def open_issues(self) -> int: ...
    @property
    def state(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def updated_at(self) -> datetime: ...
    @property
    def url(self) -> str: ...
