from typing import Any, Dict
from github.GithubObject import CompletableGithubObject

class NamedEnterpriseUser(CompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def github_com_login(self) -> str: ...
    @property
    def github_com_name(self) -> str: ...
    @property
    def enterprise_server_user_ids(self) -> list: ...
    @property
    def github_com_user(self) -> bool: ...
    @property
    def enterprise_server_user(self) -> bool: ...
    @property
    def visual_studio_subscription_user(self) -> bool: ...
    @property
    def license_type(self) -> str: ...
    @property
    def github_com_profile(self) -> str: ...
    @property
    def github_com_member_roles(self) -> list: ...
    @property
    def github_com_enterprise_roles(self) -> list: ...
    @property
    def github_com_verified_domain_emails(self) -> list: ...
    @property
    def github_com_saml_name_id(self) -> str: ...
    @property
    def github_com_orgs_with_pending_invites(self) -> list: ...
    @property
    def github_com_two_factor_auth(self) -> bool: ...
    @property
    def enterprise_server_primary_emails(self) -> list: ...
    @property
    def visual_studio_license_status(self) -> str: ...
    @property
    def visual_studio_subscription_email(self) -> str: ...
    @property
    def total_user_accounts(self) -> int: ...
