from datetime import datetime
from github.NotificationSubject import NotificationSubject
from github.Repository import Repository
from typing import (
    Any,
    Dict,
    Optional,
)


class Notification:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def last_read_at(self) -> None: ...
    def mark_as_read(self) -> None: ...
    @property
    def reason(self) -> str: ...
    @property
    def repository(self) -> Repository: ...
    @property
    def subject(self) -> NotificationSubject: ...
    @property
    def subscription_url(self) -> str: ...
    @property
    def unread(self) -> Optional[bool]: ...
    @property
    def updated_at(self) -> datetime: ...
    @property
    def url(self) -> Optional[str]: ...
