from typing import (
    Dict,
    Union,
)


class Path:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Union[str, int]]) -> None: ...
    @property
    def count(self) -> int: ...
    @property
    def path(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def uniques(self) -> int: ...
