from typing import Any, Dict


class Permissions:
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def admin(self) -> bool: ...
    @property
    def pull(self) -> bool: ...
    @property
    def push(self) -> bool: ...
