from typing import Dict


class Permissions:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, bool]) -> None: ...
    @property
    def admin(self) -> bool: ...
    @property
    def pull(self) -> bool: ...
    @property
    def push(self) -> bool: ...
