from typing import (
    Dict,
    Union,
)


class Plan:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Union[str, int]]) -> None: ...
    @property
    def collaborators(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def private_repos(self) -> int: ...
    @property
    def space(self) -> int: ...
