from datetime import datetime
from github.NamedUser import NamedUser
from github.PaginatedList import PaginatedList
from github.ProjectColumn import ProjectColumn
from typing import (
    Dict,
    Union,
)


class Project:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Union[int, str, Dict[str, Union[str, int]]]]) -> None: ...
    @property
    def body(self) -> str: ...
    @property
    def columns_url(self) -> str: ...
    def create_column(self, name: str) -> ProjectColumn: ...
    @property
    def created_at(self) -> datetime: ...
    @property
    def creator(self) -> NamedUser: ...
    def get_columns(self) -> PaginatedList: ...
    @property
    def html_url(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def node_id(self) -> str: ...
    @property
    def number(self) -> int: ...
    @property
    def owner_url(self) -> str: ...
    @property
    def state(self) -> str: ...
    @property
    def updated_at(self) -> datetime: ...
    @property
    def url(self) -> str: ...
