from datetime import datetime
from github.GithubObject import _NotSetType
from github.Issue import Issue
from github.NamedUser import NamedUser
from github.PullRequest import PullRequest
from typing import (
    Dict,
    Optional,
    Union,
)


class ProjectCard:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Union[str, int, Dict[str, Union[str, int]], None]]) -> None: ...
    @property
    def archived(self) -> bool: ...
    @property
    def column_url(self) -> str: ...
    @property
    def content_url(self) -> Optional[str]: ...
    @property
    def created_at(self) -> datetime: ...
    @property
    def creator(self) -> NamedUser: ...
    def get_content(
        self,
        content_type: Union[_NotSetType, str] = ...
    ) -> Optional[Union[PullRequest, Issue]]: ...
    @property
    def id(self) -> int: ...
    @property
    def node_id(self) -> str: ...
    @property
    def note(self) -> None: ...
    @property
    def updated_at(self) -> datetime: ...
    @property
    def url(self) -> str: ...
