from typing import Any, Dict

from github.GithubObject import CompletableGithubObject

class PublicKey(CompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def key_id(self) -> str: ...
    @property
    def key(self) -> str: ...
    def encrypt(self, unencrypted_value: str) -> str: ...
