from typing import (
    Dict,
    Union,
)


class PullRequestMergeStatus:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Union[bool, str]]) -> None: ...
    @property
    def merged(self) -> bool: ...
    @property
    def message(self) -> str: ...
    @property
    def sha(self) -> str: ...
