from datetime import datetime
from typing import Dict


class Rate:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, int]) -> None: ...
    @property
    def limit(self) -> int: ...
    @property
    def remaining(self) -> int: ...
    @property
    def reset(self) -> datetime: ...
