from github.Rate import Rate
from typing import Dict


class RateLimit:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Dict[str, int]]) -> None: ...
    @property
    def core(self) -> Rate: ...
    @property
    def graphql(self) -> Rate: ...
    @property
    def search(self) -> Rate: ...
