from datetime import datetime
from github.NamedUser import NamedUser
from typing import (
    Any,
    Dict,
)


class Reaction:
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def content(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...
    def delete(self) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def user(self) -> NamedUser: ...
