from typing import (
    Dict,
    Union,
)


class RepositoryKey:
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Union[str, int]]) -> None: ...
    def delete(self) -> None: ...
    @property
    def key(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def verified(self) -> bool: ...
