from typing import Any, Dict

from github.GithubObject import CompletableGithubObject

class RepositoryReleaseNotes(CompletableGithubObject):

    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def body(self) -> str: ...
