from typing import (
    Dict,
    List,
    Union,
)


class RequiredStatusChecks:
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Union[str, bool, List[str]]]) -> None: ...
    @property
    def contexts(self) -> List[str]: ...
    @property
    def strict(self) -> bool: ...
