import datetime
from typing import List
from github.GithubObject import CompletableGithubObject
from github.Repository import Repository

class Secret(CompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self) -> None: ...
    def delete(self) -> None: ...
    def add_repo(self, repo_name: str) -> None: ...
    def remove_repo(self, repo_name: str) -> None: ...
    def update_visibility(self, visibility: str) -> None: ...
    @property
    def secret_name(self) -> str: ...
    @property
    def created_at(self) -> datetime.datetime: ...
    @property
    def updated_at(self) -> datetime.datetime: ...
    @property
    def visibility(self) -> str: ...
    @property
    def selected_repositories(self) -> List[Repository]: ...
    @property
    def selected_repositories_url(self) -> str: ...
    @property
    def url(self) -> str: ...
