from datetime import datetime
from typing import Any, Dict

import github.GithubObject

class Secret(github.GithubObject.NonCompletableGithubObject):
    def __repr__(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...
    @property
    def name(self) -> str: ...
    @property
    def updated_at(self) -> datetime: ...
    @property
    def visibility(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
