from typing import Any, Dict

from github import AdvancedSecurity, SecretScanning, SecretScanningPushProtection
from github.GithubObject import NonCompletableGithubObject

class SecurityAndAnalysis(NonCompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def advanced_security(self) -> AdvancedSecurity: ...
    @property
    def secret_scanning(self) -> SecretScanning: ...
    @property
    def secret_scanning_push_protection(self) -> SecretScanningPushProtection: ...
