from datetime import datetime
from github.NamedUser import NamedUser
from typing import (
    Any,
    Dict,
)


class Stargazer:
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def starred_at(self) -> datetime: ...
    @property
    def user(self) -> NamedUser: ...
