from typing import List


class StatsCodeFrequency:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: List[int]) -> None: ...
    @property
    def additions(self) -> int: ...
    @property
    def deletions(self) -> int: ...
