from typing import Dict, List

class StatsParticipation:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, List[int]]) -> None: ...
    @property
    def all(self) -> List[int]: ...
    @property
    def owner(self) -> List[int]: ...
