from typing import List


class StatsPunchCard:
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: List[List[int]]) -> None: ...
    def get(self, day: int, hour: int) -> int: ...
