from github.Commit import Commit
from typing import (
    Dict,
    Union,
)


class Tag:
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Union[str, Dict[str, str]]]) -> None: ...
    @property
    def commit(self) -> Commit: ...
    @property
    def name(self) -> str: ...
    @property
    def tarball_url(self) -> str: ...
    @property
    def zipball_url(self) -> str: ...
