from typing import Any, Dict

from github.Issue import Issue

from github.GithubObject import NonCompletableGithubObject

class TimelineEventSource(NonCompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def type(self) -> str: ...
    @property
    def issue(self) -> Issue: ...
