from typing import Any, Dict

from github.GithubObject import NonCompletableGithubObject

class Tool(NonCompletableGithubObject):
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def guid(self) -> str: ...
    @property
    def version(self) -> str: ...
