from typing import Any, Dict

class Topic:
    def __repr__(self) -> str: ...
    def _initAttributes(self) -> None: ...
    def _useAttributes(self, attributes: Dict[str, Any]) -> None: ...
    @property
    def description(self) -> str: ...
    @property
    def display_name(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def short_description(self) -> str: ...
