name: Build package

on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Name of an artifact"
        type: "string"
        required: false
        default: "package"

jobs:
  build-pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -U build twine
      - name: Build 📦 package
        run: python -m build
      - name: Check 📦 package
        run: twine check dist/*

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: ${{ inputs.artifact-name }}
          path: dist
